### ISSUE TITLE
细节-RCNN关于提案框的回归

### ISSUE THREAD

**Issue by LarT2P** [lartpang/ML_markdown#10]
在后面需要对于提案框进行回归处理，但是输入网络的是对应的调整变形后的图像，所以说后面在回归的时候，用的还是原本的未调整变行前的提案框数据（这部分是可以保留下来的），变形调整只是调整了图像的大小，而并没有改变各个提案框的数据。

说明这里是需要额外保存数据的。

**Comment by lartpang** [comment]
这里是样的。
